In [1]:
import sys
sys.path.append('/Users/pepul/Library/Python/3.8/lib/python/site-packages')

import gym

In [2]:
import numpy as np
import random
import time
from IPython.display import clear_output

In [3]:
env= gym.make('FrozenLake-v1')

In [4]:
action_space_size= env.action_space.n
state_action_size= env.observation_space.n

q_table= np.zeros((state_action_size,action_space_size))
q_table

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
num_episodes = 10000
max_steps_episode = 100

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

In [6]:
rewards_all_episodes = []
for episode in range(num_episodes):
    state = env.reset()
    (state,b) = state
    done = False
    rewards_current_episode = 0
    for step in range(max_steps_episode): 

      # Exploration-exploitation trade-off
        exploration_rate_threshold = random.uniform(0, 1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state,:]) 
        else:
            action = env.action_space.sample()
        
        new_state, reward, done,truncated, info = env.step(action)
          # Update Q-table for Q(s,a)
        q_table[state, action] = q_table[state, action] * (1 - learning_rate) + learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))

        state = new_state
        rewards_current_episode += reward 

        if done == True: 
            break
            
            
    # Exploration rate decay
    exploration_rate = min_exploration_rate + (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)

    rewards_all_episodes.append(rewards_current_episode)
    
# Calculate and print the average reward per thousand episodes
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes),num_episodes/1000)
count = 1000

print("Average reward per thousand episodes\n")
for r in rewards_per_thousand_episodes:
    print(count, ": ", str(sum(r/1000)))
    count += 1000

print(q_table)

Average reward per thousand episodes

1000 :  0.03900000000000003
2000 :  0.22500000000000017
3000 :  0.4190000000000003
4000 :  0.5730000000000004
5000 :  0.6210000000000004
6000 :  0.6370000000000005
7000 :  0.6790000000000005
8000 :  0.6910000000000005
9000 :  0.6490000000000005
10000 :  0.6940000000000005
[[0.57680838 0.50082279 0.50811695 0.51111531]
 [0.30863542 0.35269322 0.34823254 0.5005782 ]
 [0.40536316 0.41008798 0.40202854 0.47801459]
 [0.23047476 0.3089273  0.37664391 0.44381762]
 [0.59063823 0.43952961 0.48690739 0.31262686]
 [0.         0.         0.         0.        ]
 [0.27197712 0.14404376 0.16317151 0.0694279 ]
 [0.         0.         0.         0.        ]
 [0.40457316 0.35620292 0.40855842 0.62106191]
 [0.45224084 0.68993342 0.54805289 0.45284781]
 [0.52973122 0.33643555 0.3834439  0.31648727]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.51287992 0.59428215 0.8263746  0.48491383]
 [0.72204761 0.91438391 0.72560

In [7]:

for episode in range(3):
    state = env.reset()
    (state,b) = state 
    
    done = False
    print("Episode: ",episode+1)
    time.sleep(1)

    for step in range(max_steps_episode):
        clear_output(wait=True)
        #env.render()
        time.sleep(0.3)
    
        
        action = np.argmax(q_table[state,:])
        
        new_state, reward, done ,truncated, info = env.step(action)

        if done:
            clear_output(wait= True)
            #env.render()
            if reward == 1:
                print('Reached the Goal')
                time.sleep(3)
            else:
                print('Fell in Hole')
                time.sleep(3)
            clear_output(wait=True)
            break
    
        state = new_state
env.close()

Reached the Goal
